Add project folder structure
BC-MAY-21-RN/kata-05-reservacion-de-vuelos-aug21-k05-t01 pull request #8
Opened 2021-09-17 17:42 UTC by Shadic78

Co-authored-by: RaulMorales404 <r20160106@gmail.com>

# Description
 - Created the project folder structure:
 - src
 -- components
 -- screens
 -- hooks
 -- redux
 -- services
 -- navigation

2021-09-17 18:07 UTC, DemisRincon submitted a review, later dismissed

2021-09-17 18:56 UTC, YilKanda requested changes
I understand the need to create a file, to create the directory tree that you are going to use, but instead of the "deleteMe.txt" file, I recommend that you use an empty "index.js" file, that way, you can use even that file if necessary.

2021-09-17 19:51 UTC, Shadic78 commented
> I understand the need to create a file, to create the directory tree that you are going to use, but instead of the "deleteMe.txt" file, I recommend that you use an empty "index.js" file, that way, you can use even that file if necessary.

Already fixed

2021-09-17 20:01 UTC, YilKanda approved these changes
LGTM!

2021-09-20 15:32 UTC, ljau approved these changes

2021-09-20 15:32 UTC, 96vladi approved these changes

2021-09-20 15:35 UTC, merged