Feature#4 register view
BC-MAY-21-RN/kata-05-reservacion-de-vuelos-aug21-k05-t01 pull request #9
Opened 2021-09-21 16:39 UTC by Shadic78

# Description
What did you implemented/Why did you implemented this:
 - Implemented RegisterView Screen without functionality
 - Implemented TextBox component
 - Implemented CustomButton component
 - implemented CheckBoxWithLabel component

  ## Screenshots 
![image](https://user-images.githubusercontent.com/43481488/134211407-92109b74-e284-4142-97cd-32a004c06868.png)

![image](https://user-images.githubusercontent.com/43481488/134211461-3dda4385-019d-41db-a74c-a20728242f19.png)

2021-09-21 23:04 UTC, YilKanda requested changes

2021-09-21 23:04 UTC, YilKanda commented on src/components/TextBox.jsx
> +
The same from the previous comment.

2021-09-21 23:04 UTC, YilKanda commented on src/screens/RegisterView.jsx
> +});
The same from the previous comment of the styles.

2021-09-22 15:32 UTC, Shadic78 commented on src/components/CheckBoxWithLabel.jsx
> +});
I made the changes.

2021-09-22 15:40 UTC, YilKanda approved these changes
LGTM!

2021-09-22 17:31 UTC, DemisRincon submitted a review, later dismissed

2021-09-22 20:43 UTC, jkzasori reviewed
Please, resolve the conflicts and try again.

2021-09-23 15:22 UTC, robermancera approved these changes

2021-09-23 15:30 UTC, 96vladi approved these changes

2021-09-23 15:30 UTC, ljau approved these changes

2021-09-23 15:37 UTC, jkzasori approved these changes

2021-09-23 15:39 UTC, merged